[project]
name = "myproject"
version = "0.1.0"
description = ""
dependencies = [
    "datasets>=4.4.1",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.7",
    "numpy>=2.2.6",
    "pyarrow>=22.0.0",
    "tiktoken>=0.12.0",
    "torch>=2.9.0",
    "wandb>=0.23.0",
]

[dependencies]

[settings]
