[package]
name = "rust_tokenizer"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23", features = ["extension-module"] }
fancy-regex = "0.13"
ahash = "0.8"
compact_str = "0.8"
rayon = "1.7"
